repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-json
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files"]
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0  
  hooks:
    - id: interrogate
      name: interrogate
      exclude: ^(docs|playground|tests)
      entry: interrogate
      args: [-v, --fail-under=95, --ignore-module]

